services:
  tw_stock_dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nk7260ynpa/tw_stock_dashboard:latest
    container_name: tw_stock_dashboard
    ports:
      - "8002:8000"
    volumes:
      - ../logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
